import { Person } from '../src/SwApi';

export const personsMock: Person[] = [
    {
        birth_year: '19 BBY',
        eye_color: 'Blue',
        films: [],
        gender: 'male',
        hair_color: 'Blond',
        height: '172',
        homeworld: 'https://swapi.dev/api/planets/1/',
        mass: '77',
        name: 'Luke Skywalker',
        skin_color: 'Fair',
        created: '2014-12-09T13:50:51.644000Z',
        edited: '2014-12-10T13:52:43.172000Z',
        species: [],
        starships: [],
        url: 'https://swapi.dev/api/people/1/',
        vehicles: [
            'https://swapi.dev/api/vehicles/14/',
        ],
        homeworld_id: 1,
        id: 1,
    },
    {
        name: 'C-3PO',
        height: '167',
        mass: '75',
        hair_color: 'n/a',
        skin_color: 'gold',
        eye_color: 'yellow',
        birth_year: '112BBY',
        gender: 'n/a',
        homeworld: 'http://swapi.dev/api/planets/1/',
        films: [],
        species: [],
        vehicles: [],
        starships: [],
        created: '2014-12-10T15:10:51.357000Z',
        edited: '2014-12-20T21:17:50.309000Z',
        url: 'http://swapi.dev/api/people/2/',
        id: 2,
        homeworld_id: 1,
    },
];
